[workspace]
members = ["cargo:."]

[dist.github-custom-runners]
global = "ubuntu-latest"

[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-latest"

[dist.github-custom-runners.aarch64-unknown-linux-musl]
runner = "ubuntu-latest"

[dist.github-custom-runners.armv7-unknown-linux-gnueabihf]
runner = "ubuntu-latest"

[dist.github-custom-runners.armv7-unknown-linux-musleabihf]
runner = "ubuntu-latest"

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-latest"

[dist.github-custom-runners.x86_64-unknown-linux-musl]
runner = "ubuntu-latest"

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.29.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-unknown-linux-musl", "armv7-unknown-linux-gnueabihf", "armv7-unknown-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]
